/**
 * cindy-bridge —— 写进 pi agentHome/extensions/ 的扩展源码(字符串常量)。
 *
 * 这段代码跑在 **pi 子进程**(bun runtime)里,不能 import cindy 任何模块;
 * 只依赖 pi 的 ExtensionAPI、fetch 与 node:fs。职责:
 *  1. 权限门:tool_call 拦截。bypassPermissions 放行;ask 档下只读内置工具放行,
 *     其余(bash/edit/write + 全部桥接 MCP 工具)经 ctx.ui.confirm 走 cindy 审批
 *     (RPC 模式 → extension_ui_request → PiAgent → interactionResolver)。
 *     权限档从 CINDY_PI_PERMISSION_FILE 每次现读 —— setPermissionMode 热切换生效;
 *     读不到一律按 ask(fail-closed)。
 *  2. MCP 桥:CINDY_PI_MCP_BRIDGE 指向 host 的 localhost bridge，或用户显式配置的
 *     外部 Streamable HTTP MCP。外部认证只保存 env 引用，真值留在 Pi 父进程 env；
 *     对每个 server 走 initialize → 分页 tools/list,把工具注册成 pi 工具
 *     (mcp__<server>__<tool>),execute 转发 tools/call。
 *  3. 会话树:注册 Cindy 私有 command，把 RPC prompt 桥到 ctx.navigateTree。
 *
 * 协议说明(@modelcontextprotocol/sdk StreamableHTTPServerTransport):
 *  - POST 单条 JSON-RPC;Accept 必须同时含 application/json 与 text/event-stream;
 *  - initialize 响应头 mcp-session-id,后续请求回带;
 *  - 响应可能是 application/json 或 SSE(请求-响应模式下 server 发完即关流,
 *    text() 可整体读取后解析);notification 返回 202 空体。
 *
 * 更新方式:PiAgent 每次 startSession 覆写该文件;改这里 = 改下次会话的桥行为。
 */

import { SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS } from '../shared/sensitive-credential-paths.js';

export const CINDY_BRIDGE_EXTENSION_FILENAME = 'cindy-bridge.ts';

export const CINDY_BRIDGE_EXTENSION_SOURCE = String.raw`/**
 * cindy-bridge (generated by Cindy — do not edit; overwritten on session start)
 */
import { readFileSync, realpathSync } from 'node:fs';
import path from 'node:path';
import { createBashTool } from '@earendil-works/pi-coding-agent';

const PERMISSION_TITLE = 'cindy:permission';
const READONLY_BUILTINS = new Set(['read', 'grep', 'find', 'ls']);
const FILE_WRITE_BUILTINS = new Set(['edit', 'write']);

// Pi 的模型鉴权、localhost proxy 与 MCP bearer 需要留在父进程 env 供 runtime
// 按请求解析，但绝不能继承进 LLM 可调用的 bash 子进程。名单由 host 按本次会话
// 实际注入的动态 BYOM env 生成；permission file 同样隐藏，避免一次获批的 bash
// 通过改写权限档给后续工具永久提权。
const SECRET_ENV_NAMES = new Set<string>([
  'CINDY_PI_SECRET_ENV_NAMES',
  'CINDY_PI_PERMISSION_FILE',
  'PI_CODING_AGENT_DIR',
]);
try {
  const names = JSON.parse(process.env.CINDY_PI_SECRET_ENV_NAMES ?? '[]');
  if (Array.isArray(names)) {
    for (const name of names) {
      if (typeof name === 'string' && name.length > 0) SECRET_ENV_NAMES.add(name);
    }
  }
} catch {
  // host 生成的配置若损坏，仍至少隐藏名单变量与 permission file；权限门继续 fail closed。
}

function withoutPiSecrets(env: Record<string, string | undefined>): Record<string, string | undefined> {
  const clean = { ...env };
  for (const name of SECRET_ENV_NAMES) delete clean[name];
  return clean;
}

// 凭证/密钥路径特征由 maker-core 的单一来源生成。bridge 自包含、运行时不能 import，
// 但不再维护第二份手写名单，避免新增凭证目录时 Pi 静默漏拦。
const CREDENTIAL_PATH_PATTERNS = ${JSON.stringify(SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS)}
  .map(({ source, flags }) => new RegExp(source, flags));

// 递归扫全部字符串叶子(含数组 / 嵌套对象),深度上限防环/超大入参。工具入参把路径
// 放进 { paths: [...] } 或 { opts: { path } } 时也能命中,不止顶层 string 字段。
function touchesCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(input));
  if (Array.isArray(input)) return input.some((v) => touchesCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => touchesCredentialPath(v, depth + 1));
  }
  return false;
}

// 未解析的路径字符串命不中凭证特征,但工作区内的符号链接可指向 /proc/self/environ 等
// 敏感目标;path.resolve 不跟随链接,故 touchesCredentialPath 会漏判(greptile 报)。这里
// 对每个字符串叶子额外 realpathSync 跟随链接,用**解析后**的真实目标再匹配一次特征。
// realpathSync 对不存在/非路径字符串会抛,catch 即跳过(仍有原始字符串检查兜底)。
function resolvesToCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') {
    if (!input) return false;
    try {
      const resolved = realpathSync(input);
      return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(resolved));
    } catch {
      return false;
    }
  }
  if (Array.isArray(input)) return input.some((v) => resolvesToCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => resolvesToCredentialPath(v, depth + 1));
  }
  return false;
}

// 从 bash 子进程读取任意进程的初始环境(/proc/<pid|self>/environ)是绕过密钥剥离的旁路:
// spawn 边界虽从子进程 env 删了 Cindy 私密变量,但父 pi 进程仍持有它们,同 UID 下
// cat /proc/PPID/environ 可直接取回代理 token / 网关 key / BYOM key(codex 报)。
// 无法从 JS 侧让 /proc 不可读,故在工具边界对这类命令一律硬拦(含 Full access)。
// 线程视图 /proc/<pid>/task/<tid>/environ(乃至其它中间段)与 /proc/<pid>/environ 等价可读,
// 同样拦。中间段允许含斜杠(旧正则用 [^/...]* 只认单段,漏了 task/<tid>,codex report),
// 与 readonly-builtin 硬拦所用的共享 SENSITIVE_CREDENTIAL_PATH 特征(/proc/[^斜杠空白]*/environ)
// 保持同等覆盖。注:命令文本匹配不是安全边界(变形/间接读取可绕过,详见 pi-harness.md 的
// Full access 契约),这里只是 defense-in-depth。
// (本文件是 String.raw 模板,注释里严禁反引号,否则会提前终结模板。)
const PROC_ENVIRON_READ_RE = /\/proc\/[^\s'"]*\/environ\b/i;
function commandReadsProcessEnviron(command: unknown): boolean {
  return typeof command === 'string' && PROC_ENVIRON_READ_RE.test(command);
}

function currentPermissionState(): {
  mode: 'ask' | 'bypassPermissions';
  readOnlyRoots: string[];
} {
  const file = process.env.CINDY_PI_PERMISSION_FILE ?? '';
  if (!file) return { mode: 'ask', readOnlyRoots: [] };
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    return {
      mode: parsed?.mode === 'bypassPermissions' ? 'bypassPermissions' : 'ask',
      readOnlyRoots: Array.isArray(parsed?.readOnlyRoots)
        ? parsed.readOnlyRoots.filter((root: unknown) => typeof root === 'string')
        : [],
    };
  } catch {
    return { mode: 'ask', readOnlyRoots: [] };
  }
}

function isInsideRoot(candidate: string, root: string): boolean {
  const target = path.resolve(candidate);
  const base = path.resolve(root);
  const rel = path.relative(base, target);
  return rel === '' || (!rel.startsWith('..' + path.sep) && rel !== '..' && !path.isAbsolute(rel));
}

// ── MCP streamable-HTTP 极简 client ─────────────────────────────────────────

interface McpServerRef {
  name: string;
  url: string;
  remote?: {
    headerEnvVars: Record<string, string>;
    startupTimeoutMs: number;
    requestTimeoutMs: number;
  };
}

class McpBridgeError extends Error {}

function safeMcpFailure(error: unknown): string {
  return error instanceof McpBridgeError ? error.message : 'unexpected error';
}

function isLoopbackMcpHostname(hostname: string): boolean {
  const normalized = hostname.toLowerCase();
  return normalized === 'localhost'
    || normalized === '127.0.0.1'
    || normalized === '::1'
    || normalized === '[::1]';
}

function isAllowedMcpUrl(url: URL): boolean {
  if (url.username || url.password) return false;
  if (url.protocol === 'https:') return true;
  return url.protocol === 'http:' && isLoopbackMcpHostname(url.hostname);
}

class McpHttpClient {
  private nextId = 1;
  private sessionId: string | null = null;
  private readonly requestUrl: string;
  private readonly requestTimeoutMs: number;
  private startupDeadlineAt: number | null;

  constructor(
    private readonly server: McpServerRef,
    private readonly token: string,
  ) {
    let parsed: URL;
    try {
      parsed = new URL(server.url);
    } catch {
      throw new McpBridgeError('invalid URL');
    }
    // 外部 URL 的 host 边界由用户保存的 endpoint 决定；这里再做 web-only fail-closed，
    // 防描述符损坏后把 Pi 变成 file/data 等协议读取器。非 loopback 必须 HTTPS；URL
    // 内嵌凭证也禁止，避免它们进入 bridge JSON，认证必须走专用 env。
    if (!isAllowedMcpUrl(parsed)) {
      throw new McpBridgeError('URL outside security boundary');
    }
    this.requestUrl = parsed.href;
    const configuredTimeout = server.remote?.requestTimeoutMs;
    this.requestTimeoutMs = Number.isInteger(configuredTimeout)
      && configuredTimeout! > 0
      && configuredTimeout! <= 600_000
      ? configuredTimeout!
      : 600_000;
    const configuredStartupTimeout = server.remote?.startupTimeoutMs;
    const startupTimeoutMs = Number.isInteger(configuredStartupTimeout)
      && configuredStartupTimeout! > 0
      && configuredStartupTimeout! < 30_000
      ? configuredStartupTimeout!
      : 10_000;
    this.startupDeadlineAt = Date.now() + startupTimeoutMs;
  }

  private nextRequestTimeoutMs(): number {
    if (this.startupDeadlineAt === null) return this.requestTimeoutMs;
    const remaining = this.startupDeadlineAt - Date.now();
    if (remaining <= 0) throw new McpBridgeError('startup timed out');
    return Math.max(1, Math.min(this.requestTimeoutMs, remaining));
  }

  finishStartup(): void {
    this.startupDeadlineAt = null;
  }

  private headers(): Headers {
    const h = new Headers();
    try {
      if (this.server.remote) {
        for (const [headerName, envName] of Object.entries(this.server.remote.headerEnvVars ?? {})) {
          if (typeof envName !== 'string' || !envName) {
            throw new McpBridgeError('invalid authentication configuration');
          }
          const value = process.env[envName];
          if (value === undefined) throw new McpBridgeError('missing authentication environment');
          h.set(headerName, value);
        }
      } else {
        if (!this.token) throw new McpBridgeError('missing local bridge token');
        h.set('authorization', 'Bearer ' + this.token);
      }
      // 协议 header 与 server 颁发的 session id 由 client 掌控，不能被自定义 header 覆盖。
      h.set('content-type', 'application/json');
      h.set('accept', 'application/json, text/event-stream');
      h.delete('mcp-session-id');
      if (this.sessionId) h.set('mcp-session-id', this.sessionId);
    } catch (error) {
      if (error instanceof McpBridgeError) throw error;
      throw new McpBridgeError('invalid authentication header');
    }
    return h;
  }

  private async post<T>(body: unknown, consume: (response: Response) => Promise<T>): Promise<T> {
    const requestTimeoutMs = this.nextRequestTimeoutMs();
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), requestTimeoutMs);
    try {
      const res = await fetch(this.requestUrl, {
        method: 'POST',
        headers: this.headers(),
        body: JSON.stringify(body),
        redirect: 'error',
        signal: controller.signal,
      });
      const sid = res.headers.get('mcp-session-id');
      if (sid) this.sessionId = sid;
      // consume 在同一个 AbortController 生命周期内完成，故 200/SSE 响应头后卡住的
      // body 也会按 requestTimeoutMs 中止，不会无限阻塞后续 server 注册。
      return await consume(res);
    } catch (error) {
      if (controller.signal.aborted) throw new McpBridgeError('request timed out');
      if (error instanceof McpBridgeError) throw error;
      if (error instanceof SyntaxError) throw new McpBridgeError('invalid JSON response');
      throw new McpBridgeError('request failed');
    } finally {
      clearTimeout(timeout);
    }
  }

  /** 按 SSE event 增量取当前 JSON-RPC response；server 保持流打开也不阻塞。 */
  private async readSseResponse(res: Response, id: number): Promise<any> {
    const reader = res.body?.getReader();
    if (!reader) throw new McpBridgeError('invalid SSE response');
    const decoder = new TextDecoder();
    let buffered = '';
    const parseEvent = (eventText: string): any | null => {
      const data = eventText
        .split(/\r\n|\r|\n/)
        .filter((line) => line.startsWith('data:'))
        .map((line) => {
          const value = line.slice(5);
          return value.startsWith(' ') ? value.slice(1) : value;
        })
        .join('\n');
      if (!data) return null;
      try {
        const msg = JSON.parse(data);
        if (msg && msg.id === id && ('result' in msg || 'error' in msg)) return msg;
      } catch {
        // 其它 event / 非 JSON data 不属于当前 response，继续读流。
      }
      return null;
    };

    try {
      for (;;) {
        const { done, value } = await reader.read();
        if (value) buffered += decoder.decode(value, { stream: true });
        if (done) buffered += decoder.decode();

        for (;;) {
          const boundary = /\r\n\r\n|\n\n|\r\r/.exec(buffered);
          if (!boundary) break;
          const eventText = buffered.slice(0, boundary.index);
          buffered = buffered.slice(boundary.index + boundary[0].length);
          const msg = parseEvent(eventText);
          if (msg) return msg;
        }
        if (buffered.length > 1_048_576) {
          throw new McpBridgeError('invalid SSE response');
        }
        if (done) {
          const msg = parseEvent(buffered);
          if (msg) return msg;
          throw new McpBridgeError('invalid SSE response');
        }
      }
    } finally {
      // 找到当前 response 后不等待 server 关闭持续流，立即释放连接。
      void reader.cancel().catch(() => {});
    }
  }

  /** 解析 application/json 或 SSE 响应体里 id 匹配的 JSON-RPC response。 */
  private async readResponse(res: Response, id: number): Promise<any> {
    const contentType = res.headers.get('content-type') ?? '';
    if (!res.ok) {
      // 远端错误体可能回显 Authorization / API key，绝不拼进 Pi stderr。
      void res.body?.cancel().catch(() => {});
      throw new McpBridgeError('HTTP ' + res.status);
    }
    if (contentType.includes('text/event-stream')) {
      return this.readSseResponse(res, id);
    }
    return res.json();
  }

  async request(method: string, params?: unknown): Promise<any> {
    const id = this.nextId++;
    const msg = await this.post(
      { jsonrpc: '2.0', id, method, ...(params !== undefined ? { params } : {}) },
      (res) => this.readResponse(res, id),
    );
    if (msg.error) {
      throw new McpBridgeError('MCP ' + method + ' returned an error');
    }
    return msg.result;
  }

  async notify(method: string, params?: unknown): Promise<void> {
    await this.post(
      { jsonrpc: '2.0', method, ...(params !== undefined ? { params } : {}) },
      async (res) => { await res.body?.cancel(); },
    ).catch(() => {});
  }

  async initialize(): Promise<void> {
    await this.request('initialize', {
      protocolVersion: '2025-03-26',
      capabilities: {},
      clientInfo: { name: 'cindy-pi-bridge', version: '1.0.0' },
    });
    await this.notify('notifications/initialized');
  }
}

function mcpContentToPi(content: unknown): Array<Record<string, unknown>> {
  const out: Array<Record<string, unknown>> = [];
  if (Array.isArray(content)) {
    for (const item of content) {
      if (!item || typeof item !== 'object') continue;
      const rec = item as Record<string, unknown>;
      if (rec.type === 'text' && typeof rec.text === 'string') {
        out.push({ type: 'text', text: rec.text });
      } else if (rec.type === 'image' && typeof rec.data === 'string') {
        out.push({ type: 'image', data: rec.data, mimeType: rec.mimeType ?? 'image/png' });
      } else {
        out.push({ type: 'text', text: JSON.stringify(rec) });
      }
    }
  }
  if (out.length === 0) out.push({ type: 'text', text: '(empty result)' });
  return out;
}

async function connectServer(pi: any, server: McpServerRef, token: string): Promise<number> {
  const client = new McpHttpClient(server, token);
  await client.initialize();
  const tools: any[] = [];
  const seenCursors = new Set<string>();
  let cursor: string | undefined;
  for (;;) {
    const listed = await client.request('tools/list', cursor === undefined ? {} : { cursor });
    if (Array.isArray(listed?.tools)) tools.push(...listed.tools);
    if (!listed || typeof listed !== 'object' || !('nextCursor' in listed)) break;
    const nextCursor = listed.nextCursor;
    if (typeof nextCursor !== 'string' || seenCursors.has(nextCursor)) {
      throw new McpBridgeError('invalid tools pagination');
    }
    seenCursors.add(nextCursor);
    cursor = nextCursor;
  }
  client.finishStartup();
  for (const tool of tools) {
    const qualifiedName = 'mcp__' + server.name + '__' + tool.name;
    const parameters =
      tool.inputSchema && typeof tool.inputSchema === 'object'
        ? tool.inputSchema
        : { type: 'object', properties: {}, additionalProperties: true };
    try {
      pi.registerTool({
        name: qualifiedName,
        label: server.name + ': ' + tool.name,
        description: typeof tool.description === 'string' && tool.description.length > 0
          ? tool.description
          : 'MCP tool ' + tool.name + ' from ' + server.name,
        parameters,
        async execute(_toolCallId: string, params: unknown) {
          const result = await client.request('tools/call', {
            name: tool.name,
            arguments: params ?? {},
          });
          const content = mcpContentToPi(result?.content);
          if (result?.isError) {
            const text = content
              .map((c) => (typeof c.text === 'string' ? c.text : ''))
              .join('\n')
              .trim();
            throw new Error(text.length > 0 ? text : 'MCP tool ' + tool.name + ' failed');
          }
          return { content, details: result?.structuredContent ?? {} };
        },
      });
    } catch (err) {
      console.error('[cindy-bridge] register ' + qualifiedName + ' failed: ' + String(err));
    }
  }
  return tools.length;
}

export default async function cindyBridge(pi: any) {
  // 覆盖内置 bash：保持 Pi 原生执行/截断/取消语义，只在 spawn 边界剥离 Cindy
  // 私密变量。模型仍可正常发请求，但它执行的任意命令拿不到 proxy/MCP/BYOM 凭证。
  const bashTool = createBashTool(process.cwd(), {
    // PI_SESSION_FILE 会暴露 agentHome，继而让一次获批的 shell 定位并篡改
    // permission file；其余 PI_SESSION_* 元数据对完成编码任务也不是必需能力。
    exposeSessionEnvironment: false,
    spawnHook: ({ command, cwd, env }) => ({
      command,
      cwd,
      env: withoutPiSecrets(env),
    }),
  });
  pi.registerTool({
    ...bashTool,
    execute: async (id: string, params: unknown, signal: AbortSignal, onUpdate: unknown) =>
      bashTool.execute(id, params as any, signal, onUpdate as any),
  });

  // ── 原生会话树桥 ──────────────────────────────────────────────────────────
  // RPC 没有 navigate_tree command；ExtensionCommandContext 才暴露 navigateTree。
  // 参数用 percent-encoded JSON，避免 prompt 命令的空格/斜杠解析污染 payload。
  pi.registerCommand('cindy-branch-switch', {
    description: 'Cindy internal session branch navigation',
    handler: async (args: string, ctx: any) => {
      let payload: {
        entryId?: unknown;
        summarize?: unknown;
        customInstructions?: unknown;
        label?: unknown;
      };
      try {
        payload = JSON.parse(decodeURIComponent(args.trim()));
      } catch {
        throw new Error('Invalid Cindy branch payload');
      }
      if (typeof payload.entryId !== 'string' || payload.entryId.length === 0 || payload.entryId.length > 128) {
        throw new Error('Invalid Cindy branch entry id');
      }
      const customInstructions = typeof payload.customInstructions === 'string'
        ? payload.customInstructions.trim().slice(0, 4000)
        : undefined;
      const label = typeof payload.label === 'string'
        ? payload.label.trim().slice(0, 120)
        : undefined;
      await ctx.waitForIdle();
      await ctx.navigateTree(payload.entryId, {
        summarize: payload.summarize === true,
        ...(customInstructions ? { customInstructions } : {}),
        ...(label ? { label } : {}),
      });
    },
  });

  // ── 权限门 ────────────────────────────────────────────────────────────────
  pi.on('tool_call', async (event: any, ctx: any) => {
    const permission = currentPermissionState();
    // Extra Dirs 的结构化写工具永远禁止，即使 Full access 也不能把“只读引用”静默
    // 升级成写目录。bash 仍由 Cindy 审批/模型指令约束（Pi 暂无 OS sandbox API）。
    const targetPath = typeof event.input?.path === 'string' ? event.input.path : '';
    if (
      targetPath
      && FILE_WRITE_BUILTINS.has(event.toolName)
      && permission.readOnlyRoots.some((root) => isInsideRoot(targetPath, root))
    ) {
      return { block: true, reason: 'Cindy extra reference directories are read-only.' };
    }
    // bash 读取任意进程的初始环境(/proc/<pid|self>/environ)是绕过密钥剥离的旁路:
    // spawn 边界虽删了子进程 env 的私密变量,父 pi 进程仍持有,cat /proc/PPID/environ
    // 同 UID 直取代理 token / 网关 / BYOM key(codex 报)→ 一律硬拦,含 Full access。
    if (event.toolName === 'bash' && commandReadsProcessEnviron(event.input?.command)) {
      return { block: true, reason: 'Cindy blocks reading process environment (/proc/*/environ), even with Full access.' };
    }
    // 凭证/密钥路径的内置只读工具(read/grep/find/ls)在 Pi 父进程内执行,而父进程 env
    // 必须保留代理会话 token 与 BYOM keys($ENV 请求期解析、bridge client 使用)。Full
    // access 若放行 read /proc/self/environ 这类路径,模型可直接取 token 调回环代理,
    // 绕过审批盗刷当前会话额度(greptile 报)→ 即使 bypassPermissions 也硬拦。原始路径
    // 命不中时还要跟随符号链接:工作区内的 link 可指向敏感目标,realpath 后再判一次。
    const credentialRead = READONLY_BUILTINS.has(event.toolName)
      && (touchesCredentialPath(event.input) || resolvesToCredentialPath(event.input));
    if (credentialRead && permission.mode === 'bypassPermissions') {
      return { block: true, reason: 'Cindy blocks reading credential or key paths, even with Full access.' };
    }
    if (permission.mode === 'bypassPermissions') return;
    if (READONLY_BUILTINS.has(event.toolName) && !credentialRead) return;
    let approved = false;
    try {
      approved = await ctx.ui.confirm(
        PERMISSION_TITLE,
        JSON.stringify({ toolName: event.toolName, input: event.input ?? {} }),
      );
    } catch {
      approved = false;
    }
    if (!approved) {
      return { block: true, reason: 'User denied this tool call via Cindy.' };
    }
  });

  // ── MCP 桥 ────────────────────────────────────────────────────────────────
  const raw = process.env.CINDY_PI_MCP_BRIDGE;
  if (!raw) return;
  let cfg: { token?: string; servers?: McpServerRef[] };
  try {
    cfg = JSON.parse(raw);
  } catch {
    console.error('[cindy-bridge] invalid CINDY_PI_MCP_BRIDGE JSON');
    return;
  }
  const token = cfg.token ?? '';
  // 全部 server 并行启动：每个 remote 有独立短预算，多个黑洞 provider 也只占一份
  // startup window，不会串行叠加到 Pi RPC 的 30s ready 超时。
  await Promise.all((cfg.servers ?? []).map(async (server) => {
    try {
      const count = await connectServer(pi, server, token);
      console.error('[cindy-bridge] connected ' + server.name + ' (' + count + ' tools)');
    } catch (err) {
      console.error('[cindy-bridge] connect ' + server.name + ' failed: ' + safeMcpFailure(err));
    }
  }));
}
`;
