import { UI_ACTION_TRIGGER_PREFIX, type QueuedMessage } from '@/lib/makerChatStore';
import { stripChatQuoteMarkerLines } from '@/lib/chatQuotes';
import {
  CONTINUE_AFTER_APP_EXIT_PROMPT,
  CONTINUE_AFTER_ERROR_PROMPT,
} from '../../../shared/interruptedTurn';

export interface PendingQueueRowPresentation {
  isOrca: boolean;
  /**
   * scheduler 撞忙排队的心跳消息(origin.kind === 'scheduler'):机器生成,
   * 与 orca 同样保留重排/删除、禁止编辑/steer;行首显示任务名徽标,让用户
   * 一眼看出"这是排队等待的自动化任务"。
   */
  isScheduler: boolean;
  senderLabel: string | null;
  displayText: string;
  canEdit: boolean;
  canSteer: boolean;
  /**
   * 带 [UI_ACTION_TRIGGER] 前缀的合成指令行(续跑重试、Mivo 图片按钮等都可能
   * 在 session 忙时排进 pendingQueue,drain 前的 projection 或 drain 被 busy
   * 挡住时会短暂/持续出现在队列面板)。裸 prompt 不能给用户看,面板按此标记
   * 显示 i18n 遮蔽标签;也不许编辑/steer(任何合成指令都不该被改写)。
   */
  isSyntheticTrigger: boolean;
  /**
   * 遮蔽标签语义(review P2:不能把「续跑」文案套到所有合成触发上——Mivo
   * 图片按钮的合成消息语义是图片操作):
   *  - 'continue':error-tail 续跑指令(精确匹配共享常量)→「继续未完成的任务」;
   *  - 'generic' :其它合成触发 →「系统指令」中性标签。
   */
  syntheticKind: 'continue' | 'generic' | null;
}

/**
 * Resolves row-level presentation and permissions for the pending queue.
 * Orca messages are generated by another agent, so they keep reorder/remove
 * affordances but cannot be edited or steered like a local user draft.
 * Scheduler heartbeat prompts follow the same machine-generated rules; their
 * display text uses persistedContent (the raw schedule prompt) so the hidden
 * silent-run protocol suffix in `text` never surfaces in the queue panel.
 */
export function getPendingQueueRowPresentation(entry: QueuedMessage): PendingQueueRowPresentation {
  const origin = entry.origin;
  const isOrca = origin?.kind === 'orca';
  const isScheduler = origin?.kind === 'scheduler';
  const isSyntheticTrigger = entry.text.startsWith(UI_ACTION_TRIGGER_PREFIX);
  const isContinueTrigger =
    entry.text === CONTINUE_AFTER_APP_EXIT_PROMPT || entry.text === CONTINUE_AFTER_ERROR_PROMPT;
  const isPendingEnqueue = entry.isPendingEnqueue === true;

  return {
    isOrca,
    isScheduler,
    senderLabel: isOrca ? origin.senderLabel : isScheduler ? origin.scheduleName : null,
    displayText: isOrca
      ? (origin.displayText ?? entry.text)
      : isScheduler
        ? entry.persistedContent || entry.text
        : entry.chatMessage.quotesEncoded === true
          ? stripChatQuoteMarkerLines(entry.text)
          : entry.text,
    canEdit: !isPendingEnqueue && !isOrca && !isScheduler && !isSyntheticTrigger,
    canSteer: !isPendingEnqueue && !isOrca && !isScheduler && !isSyntheticTrigger,
    isSyntheticTrigger,
    syntheticKind: isSyntheticTrigger ? (isContinueTrigger ? 'continue' : 'generic') : null,
  };
}

/**
 * Keep an untouched encoded quote body byte-for-byte stable. The queue editor
 * shows the markerless projection, so submitting that projection as a rewrite
 * would otherwise discard the private markers even when the user changed
 * nothing. A real edit intentionally submits the visible markerless text.
 */
export function resolvePendingQueueEditSubmission(
  entry: QueuedMessage,
  visibleText: string,
): string | null {
  return visibleText === getPendingQueueRowPresentation(entry).displayText ? null : visibleText;
}
